name: Content
description: Reminder to take care of cloud-on-rails content
title: "<Project> [- part ]"
labels: ["content"]
assignees: ["christosgalano"]
body:
  - type: markdown
    attributes:
      value: |
        After creating this issue, make sure to modify the roadmap in Christos's Blog Project.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/christosgalano/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
