name: Content
description: Issue to better manage the blog's content
title: "<Project> [- part ]"
labels: ["content"]
assignees: ["christosgalano"]
body:
  - type: markdown
    attributes:
      value: |
        ## Steps after opening:

        - Modify the roadmap in Christos's Blog Project

        ## Requirements before closing:

        - Update the blog's repository:
          - update the links to other posts: `{% post_url 20yy-mm-dd-post-title %}`
          - move the post from the `_drafts` folder to the `_posts` folder

        - Update the project's repository:
          - add link to reference the blog's post
          - update the links to other posts
          - move the post from the `docs/dev` folder to the `docs` folder
          - change visibility to **Public**

        - Share the new post in LinkedIn

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/christosgalano/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
