name: Bicep Docs

on:
  workflow_dispatch:

jobs:
  bicep-docs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate documentation for Bicep modules
        uses: christosgalano/bicep-docs@main
        with:
          input: bicep
          verbose: true
