name: Bicep Docs

on:
  workflow_dispatch:

jobs:
  bicep-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install bicep-docs
        run: go install github.com/christosgalano/bicep-docs/cmd/bicep-docs@latest
      
      - name: Generate docs
        run: bicep-docs --input ./bicep --verbose
