name: Bicep Docs

on:
  workflow_dispatch:

jobs:
  bicep-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
            Invoke-WebRequest -Uri https://github.com/christosgalano/bicep-docs/releases/download/v1.0.0/bicep-docs_windows_amd64.zip -OutFile bicep-docs.zip
            Expand-Archive -Path bicep-docs.zip -DestinationPath . -Force
      
      - name: Download Linux/MacOS
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            wget https://github.com/christosgalano/bicep-docs/releases/download/v1.0.0/bicep-docs_darwin_amd64.tar.gz -O bicep-docs.tar.gz
          else
            wget https://github.com/christosgalano/bicep-docs/releases/download/v1.0.0/bicep-docs_linux_amd64.tar.gz -O bicep-docs.tar.gz
          fi
          tar xzf bicep-docs.tar.gz
          chmod +x bicep-docs
      
      - name: Generate docs
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            .\bicep-docs.exe --input bicep --verbose
          else
            ./bicep-docs --input bicep --verbose
          fi

