# This workflows creates labels specified in scripts to all repositories.

name: create-labels
run-name: ${{ github.workflow }}

on:
  schedule:
    - cron: "0 21 * * *" # at 21:00, every day
  workflow_dispatch:

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Give execute permissions
        working-directory: ${{ github.workspace }}/.github/scripts
        run: chmod +x *.sh

      - name: Execute all scripts
        working-directory: ${{ github.workspace }}/.github/scripts
        run: |
          for script in ./*
          do
            ./$script ${{ secrets.ISSUE_MANAGER_PAT }}
          done
