# This workflows creates labels specified in scripts to all repositories.

name: create-labels
run-name: ${{ github.workflow }}

on:
  schedule:
    - cron: "0 21 * * *" # at 21:00, every day
  workflow_dispatch:
    inputs:
      bool-flag:
        description: "Test desc"
        type: boolean
  push:
    paths:
      - "workflow-templates/*yaml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ inputs.bool-flag || 'true' }}
          echo ${{ inputs.bool-flag || 'false' }}
  # create-labels:
  #   name: Create labels for all repositories
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Give execute permissions
  #       working-directory: ${{ github.workspace }}/.github/scripts
  #       run: chmod +x *.sh

  #     - name: Execute all scripts
  #       working-directory: ${{ github.workspace }}/.github/scripts
  #       run: |
  #         for script in ./*
  #         do
  #           ./$script ${{ secrets.ISSUE_MANAGER_PAT }}
  #         done
