# This workflows creates labels specified in scripts to all repositories.

name: create-labels
run-name: ${{ github.workflow }}

on:
  # schedule:
  #   - "0 9 * * *" # every day at 9 am
  workflow_dispatch:

jobs:
  create-labels:
    name: Create labels for all repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Give execute permissions
        working-directory: ${{ github.workspace }}/.github/scripts
        run: chmod +x *.sh

      - name: Execute all scripts
        working-directory: ${{ github.workspace }}/.github/scripts
        run: |
          for script in ./*
          do
            ./$script ${{ secrets.ISSUE_MANAGER_PAT }}
          done
