# This workflows updates a label specified (or creates one if it doesn't exist) in all of the user's repositories.
name: create-update-label
run-name: ${{ github.workflow }}
on:
  schedule:
    - cron: "0 21 * * *" # at 21:00, every day
  workflow_dispatch:
    inputs:
      name:
        description: "Specify label name"
        default: content
        required: true
        type: string
      color:
        description: "Specify label color"
        default: 252a30
        required: true
        type: string
      description:
        description: "Specify label description"
        default: "Blog-related"
        required: true
        type: string

jobs:
  create-update-label:
    runs-on: ubuntu-latest
    steps:
      - uses: christosgalano/Workflows-Actions-Library/.github/actions/create-update-label@main
        with:
          name: ${{ inputs.name || 'content' }}
          color: ${{ inputs.color || '252a30' }}
          description: ${{ inputs.description || 'Blog-related' }}
          token: ${{ secrets.ISSUE_MANAGER_PAT }}
