name: Create labels
run-name: ${{ github.workflow }}

on:
  workflow_dispatch:

jobs:
  create-labels:
    name: Create labels for all repositories
    runs-on: ubuntu-latest
    steps:
      - name: Get all repositories
        run: |
          repos=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ISSUE_MANAGER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/repos)

      - name: Clean the repositories
        run: |
          repos_cleaned=( $(echo $repos | jq -r '.[].full_name') )

      - name: Print the repositories
        run: |
          echo $repos_cleaned
          printf "\n\n"
          for r in $repos_cleaned
          do
            echo "Hello: $r"
          done
