# This workflows deletes the runs of all the workflows in a repository.
name: delete-workflow-runs
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Specify the name of the repository"
        default: .github
        required: true
        type: string

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: christosgalano/delete-workflows-runs@v1.0.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ inputs.repo_name }}
          token: ${{ secrets.WORKFLOWS_MANAGER_PAT }}
