# This workflows creates labels specified in scripts to all repositories.

name: labels
run-name: ${{ github.workflow }}

on:
  schedule:
    - cron: "0 21 * * *" # at 21:00, every day
  workflow_dispatch:
    inputs:
      name:
        description: "Specify label name"
        default: content
        required: true
        type: string
      color:
        description: "Specify label color"
        default: 252a30
        required: true
        type: string
      description:
        description: "Specify label description"
        default: "Blog related"
        required: true
        type: string
      mode:
        description: "Specify mode"
        required: true
        type: choice
        options:
          - "create"
          - "update"

jobs:
  create-update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Give execute permissions
        working-directory: ${{ github.workspace }}/.github/scripts
        run: chmod +x label.sh

      - name: Execute label script
        working-directory: ${{ github.workspace }}/.github/scripts
        run: |
          ./label.sh \
            -n ${{ inputs.name || 'content' }} \
            -c ${{ inputs.color || '252a30' }} \
            -d ${{ inputs.description || 'Blog related' }} \
            -a ${{ secrets.ISSUE_MANAGER_PAT }} \
            -m ${{ inputs.mode || 'update' }}
