name: stale-repos-identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  identify:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run stale_repos tool
      uses: github/stale-repos@v1
      id: stale-repos
      env:
        GH_TOKEN: ${{ secrets.STALE_REPOS_TOKEN }}
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365
        ACTIVITY_METHOD: "pushed"
        ADDITIONAL_METRICS: "release,pr"

    - name: Update issue
      run: gh issue edit 4 --body-file stale_repos.md --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
