name: Stale repo identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 1 * *'

jobs:
  identify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - uses: actions/checkout@v3

    - name: Run stale_repos tool
      uses: github/stale-repos@v1
      id: stale-repos
      env:
        GH_TOKEN: ${{ secrets.STALE_REPOS_TOKEN }}
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365

    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"

    # # This next step updates an existing issue. If you want a new issue every time, remove this step and remove the `issue-number: ${{ env.issue_number }}` line below.
    # - name: Check for the stale report issue
    #   run: |
    #     ISSUE_NUMBER=$(gh search issues "Stale repository report" --match title --json number --jq ".[0].number")
    #     echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        # issue-number: ${{ env.issue_number }}
        title: Stale repository report
        content-filepath: ./stale_repos.md
        assignees: christosgalano
        token: ${{ secrets.GITHUB_TOKEN }}
