name: stale-repo-identifier

on:
  workflow_dispatch:

jobs:
  identify:
    name: Identify Stale Repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run stale_repos tool
      uses: github/stale-repos@v1
      id: stale-repos
      env:
        GH_TOKEN: ${{ secrets.STALE_REPOS_TOKEN }}
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 365

    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"

    # - name: Check for the stale report issue
    #   run: |
    #     ISSUE_NUMBER=$(gh search issues "Stale repository report" --match title --json number --jq ".[0].number")
    #     echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create issue
      run: gh issue edit 8 --body-file stale_repos.md --repo christosgalano/.github
