name: Test Go CLi

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Download Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
            Invoke-WebRequest -Uri https://github.com/christosgalano/${{ inputs.repo }}/releases/download/v1.0.0/${{ inputs.repo }}_windows_amd64.zip -OutFile ${{ inputs.repo }}.zip
            Expand-Archive -Path ${{ inputs.repo }}.zip -DestinationPath . -Force
      
      - name: Download Linux/MacOS
        if: runner.os != 'Windows'
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            wget https://github.com/christosgalano/${{ inputs.repo }}/releases/download/v1.0.0/${{ inputs.repo }}_darwin_amd64.tar.gz -O ${{ inputs.repo }}.tar.gz
          else
            wget https://github.com/christosgalano/${{ inputs.repo }}/releases/download/v1.0.0/${{ inputs.repo }}_linux_amd64.tar.gz -O ${{ inputs.repo }}.tar.gz
          fi
          tar xzf ${{ inputs.repo }}.tar.gz
          chmod +x ${{ inputs.repo }}
      
      - name: Test CLI
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./${{ inputs.repo }}.exe --help
          else
            ./${{ inputs.repo }} --help
          fi

