# This workflows gets the latest run conclusion of a specified workflow.
name: workflow-conclusion
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  workflow-conclusion:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Get repository's name
        id: get-repo-name
        run: |
          repo_name="$(cut -d '/' -f 2 <<< "${{ github.repository }}" )";
          echo "repo-name=$repo_name" >> $GITHUB_OUTPUT

      - name: Get create-update-label latest run conclusion
        uses: christosgalano/Workflows-Actions-Library/.github/actions/workflow-conclusion@main
        id: get-create-update-label
        with:
          workflow: create-update-label
          owner: ${{ github.repository_owner }}
          repository: ${{ steps.get-repo-name.outputs.repo-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print create-update-label latest run conclusion
        run: echo ${{ steps.get-create-update-label.outputs.workflow-conclusion }}

      - name: Get delete-workflow-runs latest run conclusion
        uses: christosgalano/Workflows-Actions-Library/.github/actions/workflow-conclusion@main
        id: get-delete-workflow-runs
        with:
          workflow: delete-workflow-runs
          owner: ${{ github.repository_owner }}
          repository: ${{ steps.get-repo-name.outputs.repo-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print delete-workflow-runs latest run conclusion
        run: echo ${{ steps.get-delete-workflow-runs.outputs.workflow-conclusion }}
